#!/bin/bash
################################################################################
# GPUMD Chunk Computation Feature - Standalone Installer
#
# This script installs LAMMPS-style chunk computation functionality into GPUMD
#
# Usage:
#   1. Copy this entire package directory to your GPUMD root directory
#   2. cd /path/to/GPUMD/chunk_feature_package
#   3. sh ./install.sh
#
# Author: Generated by Claude
# Date: 2025-12-11
################################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored message
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Get package directory (where this script is located)
PACKAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GPUMD root is parent directory of package
GPUMD_ROOT="$(cd "$PACKAGE_DIR/.." && pwd)"
GPUMD_SRC="${GPUMD_ROOT}/src"
MEASURE_DIR="${GPUMD_SRC}/measure"
MAIN_DIR="${GPUMD_SRC}/main_gpumd"

print_info "GPUMD Chunk Computation Feature Installer"
echo "========================================"
echo "Package directory: $PACKAGE_DIR"
echo "GPUMD directory:   $GPUMD_ROOT"
echo ""

# Check if GPUMD directory structure exists
print_info "Checking GPUMD directory structure..."

if [ ! -d "$GPUMD_SRC" ]; then
    print_error "GPUMD src directory not found: $GPUMD_SRC"
    print_error "Please place this package in the GPUMD root directory"
    print_error "Expected structure: GPUMD/chunk_feature_package/"
    exit 1
fi

if [ ! -d "$MEASURE_DIR" ]; then
    print_error "Measure directory not found: $MEASURE_DIR"
    exit 1
fi

if [ ! -d "$MAIN_DIR" ]; then
    print_error "Main directory not found: $MAIN_DIR"
    exit 1
fi

if [ ! -f "$MAIN_DIR/run.cu" ]; then
    print_error "run.cu not found: $MAIN_DIR/run.cu"
    exit 1
fi

print_success "GPUMD directory structure verified"
echo ""

# Check if source files exist in package
print_info "Checking package files..."

if [ ! -f "$PACKAGE_DIR/src/measure/compute_chunk.cuh" ]; then
    print_error "Package files not found in: $PACKAGE_DIR/src/measure/"
    print_error "Package structure may be corrupted"
    exit 1
fi

print_success "Package files verified"
echo ""

# Create backup
BACKUP_DIR="${GPUMD_ROOT}/.chunk_install_backup_$(date +%Y%m%d_%H%M%S)"
print_info "Creating backup at: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
cp "$MAIN_DIR/run.cu" "$BACKUP_DIR/run.cu.bak"
print_success "Backup created"
echo ""

# Function to check if chunk files already exist
check_existing_files() {
    local files_exist=0

    if [ -f "$MEASURE_DIR/compute_chunk.cuh" ]; then
        print_warning "compute_chunk.cuh already exists"
        files_exist=1
    fi

    if [ -f "$MEASURE_DIR/compute_chunk.cu" ]; then
        print_warning "compute_chunk.cu already exists"
        files_exist=1
    fi

    if [ -f "$MEASURE_DIR/ave_chunk.cuh" ]; then
        print_warning "ave_chunk.cuh already exists"
        files_exist=1
    fi

    if [ -f "$MEASURE_DIR/ave_chunk.cu" ]; then
        print_warning "ave_chunk.cu already exists"
        files_exist=1
    fi

    if [ $files_exist -eq 1 ]; then
        echo ""
        read -p "Files already exist. Overwrite? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_error "Installation cancelled"
            exit 1
        fi
    fi
}

check_existing_files

# Check if modifications already applied
print_info "Checking if modifications already applied..."
if grep -q "compute_chunk.cuh" "$MAIN_DIR/run.cu" 2>/dev/null; then
    print_warning "It appears chunk features may already be installed"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_error "Installation cancelled"
        exit 1
    fi
fi
echo ""

# Install new files
print_info "Installing new files..."

print_info "Copying compute_chunk.cuh..."
cp "$PACKAGE_DIR/src/measure/compute_chunk.cuh" "$MEASURE_DIR/"
print_info "Copying compute_chunk.cu..."
cp "$PACKAGE_DIR/src/measure/compute_chunk.cu" "$MEASURE_DIR/"
print_info "Copying ave_chunk.cuh..."
cp "$PACKAGE_DIR/src/measure/ave_chunk.cuh" "$MEASURE_DIR/"
print_info "Copying ave_chunk.cu..."
cp "$PACKAGE_DIR/src/measure/ave_chunk.cu" "$MEASURE_DIR/"

print_success "New files installed"
echo ""

# Modify run.cu
print_info "Modifying run.cu to register chunk commands..."

# Backup run.cu
cp "$MAIN_DIR/run.cu" "$MAIN_DIR/run.cu.tmp"

# Add include statements after the measure includes
print_info "Adding header includes..."

# Find the line with measure/compute.cuh and add after it
sed -i '/^#include "measure\/angular_rdf.cuh"$/a #include "measure/ave_chunk.cuh"' "$MAIN_DIR/run.cu"
sed -i '/^#include "measure\/compute.cuh"$/a #include "measure/compute_chunk.cuh"' "$MAIN_DIR/run.cu"

# Add command registration
print_info "Adding command registration..."

# Insert after compute_rdf block
sed -i '/} else if (strcmp(param\[0\], "compute_rdf") == 0) {/,/measure.properties.emplace_back(std::move(property));/{
/measure.properties.emplace_back(std::move(property));/a\
  } else if (strcmp(param[0], "compute_chunk") == 0) {\
    std::unique_ptr<Property> property;\
    property.reset(new ComputeChunk(param, num_param, box));\
    measure.properties.emplace_back(std::move(property));\
  } else if (strcmp(param[0], "ave_chunk") == 0) {\
    std::unique_ptr<Property> property;\
    property.reset(new AveChunk(param, num_param, measure));\
    measure.properties.emplace_back(std::move(property));
}' "$MAIN_DIR/run.cu"

print_success "run.cu modified"
echo ""

# Verify modifications
print_info "Verifying installation..."
if grep -q "compute_chunk.cuh" "$MAIN_DIR/run.cu" && \
   grep -q "ave_chunk.cuh" "$MAIN_DIR/run.cu" && \
   grep -q "compute_chunk" "$MAIN_DIR/run.cu" && \
   grep -q "ave_chunk" "$MAIN_DIR/run.cu"; then
    print_success "Verification passed"
else
    print_error "Verification failed - modifications may be incomplete"
    print_info "Restoring backup..."
    cp "$BACKUP_DIR/run.cu.bak" "$MAIN_DIR/run.cu"
    exit 1
fi
echo ""

# Clean up
rm -f "$MAIN_DIR/run.cu.tmp"

# Summary
echo "========================================"
print_success "Installation completed successfully!"
echo ""
echo "Files installed:"
echo "  - src/measure/compute_chunk.cuh"
echo "  - src/measure/compute_chunk.cu"
echo "  - src/measure/ave_chunk.cuh"
echo "  - src/measure/ave_chunk.cu"
echo ""
echo "Modified files:"
echo "  - src/main_gpumd/run.cu"
echo ""
echo "Backup location:"
echo "  - $BACKUP_DIR"
echo ""
print_info "Next steps:"
echo "  1. cd $GPUMD_SRC"
echo "  2. make clean"
echo "  3. make gpumd"
echo ""
print_info "Usage examples in:"
echo "  - $PACKAGE_DIR/examples/chunk_test_example.in"
echo "  - $PACKAGE_DIR/docs/CHUNK_IMPLEMENTATION.md"
echo ""
print_info "Usage in run.in:"
echo "  compute_chunk bin/1d z lower 1.0"
echo "  ave_chunk 10 5 50 temp density/mass file chunk.out"
echo ""
print_warning "If you encounter any issues, restore from backup:"
echo "  cp $BACKUP_DIR/run.cu.bak $MAIN_DIR/run.cu"
echo "========================================"
